version: '3.8'

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: ai_brain_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ai_brain
      - POSTGRES_USER=root
    secrets:
      - postgres_password
    volumes:
      - /data/docker/postgres/data:/var/lib/postgresql/data
      - /data/docker/postgres/logs:/var/log/postgresql
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"
    networks:
      - ai_brain_network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "ai_brain"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
    name: ai_brain_postgres_data
  postgres_logs:
    name: ai_brain_postgres_logs

networks:
  ai_brain_network:
    name: ai_brain_network
    driver: bridge

secrets:
  postgres_password:
    file: ./docker/postgres/postgres_password.txt 