name: agent-service-dev

services:
  agent_service:
    container_name: agent-service-dev-agent
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./docker:/app/docker
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/
        - path: src/core/
          action: sync+restart
          target: /app/core/
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/memory/
          action: sync+restart
          target: /app/memory/
        - path: src/tools/
          action: sync+restart
          target: /app/tools/
        - path: src/brain/
          action: sync+restart
          target: /app/brain/
        - path: src/tasks/
          action: sync+restart
          target: /app/tasks/

  streamlit_app:
    container_name: agent-service-dev-streamlit
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service:8080
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py
